[en]
	languageName = "English"
	weight =  1
[zh]
	languageName = "简体中文"
	weight =  2
	title = "Jakarta® EE: 云原生Java的新家园"
[ja]
	languageName = "日本語"
	weight =  2
	title = "Jakarta® EE: クラウドネイティブJavaの新ホーム"
