[[main]]
    name = "中国社区"
    url = "/zh/community/china"
    weight = 0

[[main]]
    name = "关于"
    url = "/zh/about/"
    weight = 1

[[main]]
    name = "规范"
    url = "/zh/specifications/"
    weight = 2

[[main]]
    name = "兼容产品"
    url = "/zh/compatibility/"
    weight = 3

[[main]]
    name = "社区"
    url = "/zh/community"
    weight = 4

[[main]]
    name = "成员"
    url = "/zh/Membership/"
    weight = 5

[[main]]
    name = "资源"
    url = "/zh/resources/"
    weight = 6

# About sub-menu
[[main]]
    name = "Jakarta EE"
    url = "/zh/"
    weight = 1
    parent = "关于"

[[main]]
    name = "Jakarta EE Working Group"
    url = "/zh/"
    weight = 2
    parent = "关于"

[[main]]
    name = "新闻"
    url = "/zh/news/"
    parent = "关于"
    weight = 5

[[main]]
    name = "新闻"
    url = "/zh/news/"
    parent = "关于"
    weight = 6

# Jakarta EE sub-menu
[[main]]
    name = "关于 Jakarta EE"
    url = "/zh/about/jakarta-ee"
    parent = "Jakarta EE"
    weight = 1

[[main]]
	name = "Why Jakarta EE"
	url = "/zh/about/why-jakarta-ee"
	parent = "Jakarta EE"
	weight = 2
	
[[main]]
    name = "常见问题"
    url = "/zh/about/faq/"
    parent = "Jakarta EE"
    weight = 2

[[main]]
    name = "发布版本"
    url = "/zh/release/"
    parent = "Jakarta EE"
    weight = 3

# Jakarta EE Group sub-menu
[[main]]
    name = "关于工作组"
    url = "/zh/about/working-group"
    weight = 1
    parent = "Jakarta EE Working Group"

[[main]]
    name = "章程"
    url = "https://eclipse.org/org/workinggroups/jakarta_ee_charter.php"
    weight = 2
    parent = "Jakarta EE Working Group"

[[main]]
    name = "商标指引"
    url = "/zh/legal/trademark_guidelines/"
    weight = 3
    parent = "Jakarta EE Working Group"

[[main]]
    name = "技术指引"
    url = "https://www.eclipse.org/ee4j/direction.php"
    weight = 4
    parent = "Jakarta EE Working Group"

[[main]]
    name = "委员会"
    url = "/zh/committees"
    parent = "Jakarta EE Working Group"
    weight = 5

[[main]]
    name = "会议纪要"
    url = "/zh/meeting_minutes/"
    parent = "Jakarta EE Working Group"
    weight = 6

# Resource sub-menu
[[main]]
    name = "概述"
    url = "/zh/resources"
    weight = 1
    parent = "资源"
    identifier = "overview_resources"

[[main]]
	name = "品牌"
	url = "/zh/resources/#branding"
	parent = "资源"
	weight = 3
	
[[main]]
    name = "数据表"
    url = "/zh/resources#datasheets"
    parent = "资源"
    weight = 4

[[main]]
    name = "文档"
    url = "/zh/resources#documentation"
    parent = "资源"
    weight = 5

[[main]]
    name = "演讲"
    url = "/zh/resources#presentations"
    parent = "资源"
    weight = 6

[[main]]
    name = "调研"
    url = "/zh/resources#surveys"
    parent = "资源"
    weight = 7

[[main]]
    name = "电子书"
    url = "/zh/resources/#ebooks"
    parent = "资源"
    weight = 8

[[main]]
    name = "白皮书"
    url = "/zh/resources/#white-papers"
    parent = "资源"
    weight = 9

[[main]]
    name = "案例研究"
    url = "/zh/resources/#cases-studies"
    parent = "资源"
    weight = 10

[[main]]
    name = "Jakarta EE 起步"
    url = "/zh/resources/#starter_jakartaee"
    parent = "资源"
    weight = 11

# specifications
[[main]]
    name = "浏览规范"
    url = "/zh/specifications/"
    weight = 1
    parent = "规范"

[[main]]
    name = "规范过程"
    url = "/zh/about/jesp/"
    weight = 2
    parent = "规范"

[[main]]
    name = "JESP向导"
    url = "/zh/committees/specification/guide/"
    parent = "规范"
    weight = 3

[[main]]
    name = "规范项目"
    url = "/zh/projects/"
    weight = 4
    parent = "规范"

# Compatible Products
[[main]]
    name = "Jakarta EE 兼容产品"
    url = "/zh/compatibility/"
    parent = "兼容产品"
    weight = 1

[[main]]
    name = "加入列表"
    url = "/zh/compatibility/get-listed/"
    parent = "兼容产品"
    weight = 2

# Community sub-menu
[[main]]
    name = "概述"
    url = "/zh/community/"
    parent = "社区"
    weight = 1
    identifier = "community"

[[main]]
    name = "Adopt a Spec 计划"
    parent = "社区"
    url = "/zh/community/adopt-a-spec/"
    weight = 2

[[main]]
    name = "博客"
    url = "/zh/blogs"
    parent = "社区"
    weight = 3

[[main]]
    name = "活动"
    url = "/zh/community/events/"
    parent = "社区"
    weight = 4

[[main]]
    name = "JakartaOne Livestream 线上活动"
    url = "https://jakartaone.org"
    parent = "社区"
    weight = 5

[[main]]
    name = "联系"
    url = "/zh/connect/"
    parent = "社区"
    weight = 6

[[main]]
    name = "技术沙龙"
    url = "/zh/community/#meetups"
    parent = "社区"
    weight = 7

[[main]]
    name = "视频"
    url = "/zh/community/videos"
    parent = "社区"
    weight = 8

[[main]]
    name = "加入社区"
    url = "/zh/community/get-involved"
    parent = "社区"
    weight = 9

[[main]]
    name = "Developer Advocate"
    url = "/zh/community/developer-advocate"
    parent = "社区"
    weight = 10

# Membership sub-menu
[[main]]
    name = "加入"
    url = "/zh/membership"
    parent = "成员"
    weight = 1

[[main]]
    name = "成员列表"
    url = "/zh/membership/members/"
    parent = "成员"
    weight = 2
