/*
 * Copyright (c) 2009, 2021 Oracle and/or its affiliates. All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v. 2.0, which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the
 * Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
 * version 2 with the GNU Classpath Exception, which is available at
 * https://www.gnu.org/software/classpath/license.html.
 *
 * SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0
 */

The following definitions that appear in the common
shareable schema(s) of Jakarta EE deployment descriptors should be
interpreted with respect to the context they are included:


Deployment Component may indicate one of the following:
    Jakarta EE application;
    application client;
    web application;
    enterprise bean;
    resource adapter;

Deployment File may indicate one of the following:
    ear file;
    war file;
    jar file;
    rar file;